pull_request_rules:
  - name: Merge on CI success and review approval
    conditions:
      - base~=master
      - "#approved-reviews-by>=2"
      - approved-reviews-by=@aws/aws-ecs-devx
      - status-success=continuous-integration/travis-ci/pr
      - -approved-reviews-by~=author
      - -title~=(WIP|wip)
      - -merged
      - -closed
      - -label~=(WIP|do-not-merge)
    actions:
      merge:
        method: squash
        strict: smart
        strict_method: merge
