queue_rules:
  - name: default
    conditions:
      - status-success=continuous-integration/travis-ci/pr

pull_request_rules:
  - name: Merge on CI success and review approval
    conditions:
      - base~=mainline
      - "#approved-reviews-by>=1"
      - approved-reviews-by=@aws/aws-ecs-devx
      - status-success=continuous-integration/travis-ci/pr
      - -approved-reviews-by~=author
      - -title~=(WIP|wip)
      - -merged
      - -closed
      - -label~=(WIP|do-not-merge)
    actions:
      queue:
        name: default
        method: squash
        commit_message_template: |
          {{ title }} (#{{ number }})

          {{ body }}

  - name: Automatically approve Dependabot PRs
    conditions:
      - base=mainline
      - status-success=continuous-integration/travis-ci/pr
      - author~=^dependabot(|-preview)\[bot\]$
      - -title~=(WIP|wip)
      - -label~=(WIP|do-not-merge)
      - -merged
      - -closed
    actions:
      review:
        type: APPROVE
      queue:
        name: default
        method: squash
        commit_message_template: |
          {{ title }} (#{{ number }})

          {{ body }}
