version: 0.2
phases:
  install:
    runtime-versions:
      golang: 1.13
  pre_build:
    commands:
      - mkdir -p /go/src/github.com/aws/amazon-ecs-cli
      - cp -R . /go/src/github.com/aws/amazon-ecs-cli/
      - cd /go/src/github.com/aws/amazon-ecs-cli/
      - echo "installing dependencies..."
      - go get github.com/wadey/gocovmerge
      - echo "building test binary..."
      - go test -coverpkg ./ecs-cli/modules/... -c -tags testrunmain -o ./bin/local/ecs-cli.test ./ecs-cli
  build:
    commands:
      - make integ-test-run-with-coverage
      - ./bin/local/ecs-cli.test
