// Copyright 2015 Amazon.com, Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//	http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

package utils

import (
	"fmt"
	"strings"
)

const (
	// the ~/.cache/ecscompose directory in which to store cached task definitions
	// changing this will cause user's caches to break.
	ProjectTDCache = "tdcache"

	// prefix added to all resources created by this application. TODO: Revisit this
	ecsComposeProjectPrefix = "ecscompose"

	// prefix for the autogenerated volume names in the task definition
	ecsVolumeNamePrefix = "volume"
)

// getTaskDefinitionName uses predefined format to generate task definition for this project
func getTaskDefinitionName(projectName string) string {
	return fmt.Sprintf("%s-%s", ecsComposeProjectPrefix, projectName)
}

// getVolumeName returns an autogenerated name for the ecs volume
func getVolumeName(suffixNum int) string {
	return fmt.Sprintf("%s-%d", ecsVolumeNamePrefix, suffixNum)
}

// GetServiceName returns a service name
func GetServiceName(projectName string) string {
	return fmt.Sprintf("%s-service-%s", ecsComposeProjectPrefix, projectName)
}

// GetStartedBy returns an autogenerated name that can be used to represent owner id for tasks
func GetStartedBy(projectName string) string {
	return fmt.Sprintf("%s-%s", ecsComposeProjectPrefix, projectName) // TODO, add taskDefHash
}

// GetFormattedContainerName returns the container name with task id prepended to it
func GetFormattedContainerName(ecsTaskId, ecsContainerName string) string {
	return fmt.Sprintf("%s/%s", ecsTaskId, ecsContainerName)
}

// GetIdFromArn extracts the id from arn
func GetIdFromArn(arn string) string {
	parts := strings.SplitN(arn, "/", 2)
	if len(parts) != 2 {
		return ""
	}
	return parts[1]
}
