// This is an autogenerated file and should not be edited.

// Copyright 2015-2017 Amazon.com, Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//	http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Package version contains constants to indicate the current version of the
// ecs-cli. It is autogenerated
package version

// Please DO NOT commit any changes to this file as these fields will be
// populated programmatically at compile time.

// The version of the ECS CLI. Will be set at the compile time
// based on the tag of the latest commit on the `master` branch. If
// no tag exists, then the version will be set to "development"
var Version string

// gitShortHash is the first 7 characters of the commit ID when the ECS CLI is
// compiled.
var gitShortHash string
