#!/bin/bash
# Copyright 2014-2016 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"). You may
# not use this file except in compliance with the License. A copy of the
# License is located at
#
#	http://aws.amazon.com/apache2.0/
#
# or in the "license" file accompanying this file. This file is distributed
# on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing
# permissions and limitations under the License.

set -ex

# Because of how gopaths work, you want a canonicalized import path even when
# developing on a fork of the repository.
# This creates a usable symlink at the canonical gopath so that go imports work
if [[ ! -d "$HOME/gopath/src/github.com/aws/amazon-ecs-cli" ]]; then
	mkdir -p "$HOME/gopath/src/github.com/aws"
	ln -s "$(pwd)" "$HOME/gopath/src/github.com/aws/amazon-ecs-cli"
fi
