#!/bin/bash
# Copyright 2015-2017 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"). You
# may not use this file except in compliance with the License. A copy of
# the License is located at
#
# 	http://aws.amazon.com/apache2.0/
#
# or in the "license" file accompanying this file. This file is
# distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF
# ANY KIND, either express or implied. See the License for the specific
# language governing permissions and limitations under the License.

set -e

version=${1:?Must specify version as the only argument (e.g. 1.0.0)}

# Normalize to working directory being build root (up one level from ./scripts)
ROOT=$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )
cd "${ROOT}"

source ./scripts/shared_env

echo -n "$version" > VERSION
export ECS_UNKNOWN_VERSION=true

cd ./ecs-cli/modules/version/
go run gen/version-gen.go
cd "${ROOT}"

git add ecs-cli/modules/version/version.go VERSION

# TODO, the changelog bump could also be automated
echo "Please edit the changelog and commit the version bump"
