// Copyright 2015-2017 Amazon.com, Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aws/amazon-ecs-cli/ecs-cli/modules/clients/aws/ssm (interfaces: Client)

// Package mock_ssm is a generated GoMock package.
package mock_ssm

import (
	reflect "reflect"

	ssm "github.com/aws/amazon-ecs-cli/ecs-cli/modules/clients/aws/ssm"
	gomock "github.com/golang/mock/gomock"
)

// MockClient is a mock of Client interface
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// GetRecommendedECSLinuxAMI mocks base method
func (m *MockClient) GetRecommendedECSLinuxAMI() (*ssm.AMIMetadata, error) {
	ret := m.ctrl.Call(m, "GetRecommendedECSLinuxAMI")
	ret0, _ := ret[0].(*ssm.AMIMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecommendedECSLinuxAMI indicates an expected call of GetRecommendedECSLinuxAMI
func (mr *MockClientMockRecorder) GetRecommendedECSLinuxAMI() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecommendedECSLinuxAMI", reflect.TypeOf((*MockClient)(nil).GetRecommendedECSLinuxAMI))
}
