// Copyright 2015-2016 Amazon.com, Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/cli/ecs/app (interfaces: ProjectFactory)

package mock_app

import (
	ecs "github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/ecs"
	cli "github.com/codegangsta/cli"
	gomock "github.com/golang/mock/gomock"
)

// Mock of ProjectFactory interface
type MockProjectFactory struct {
	ctrl     *gomock.Controller
	recorder *_MockProjectFactoryRecorder
}

// Recorder for MockProjectFactory (not exported)
type _MockProjectFactoryRecorder struct {
	mock *MockProjectFactory
}

func NewMockProjectFactory(ctrl *gomock.Controller) *MockProjectFactory {
	mock := &MockProjectFactory{ctrl: ctrl}
	mock.recorder = &_MockProjectFactoryRecorder{mock}
	return mock
}

func (_m *MockProjectFactory) EXPECT() *_MockProjectFactoryRecorder {
	return _m.recorder
}

func (_m *MockProjectFactory) Create(_param0 *cli.Context, _param1 bool) (ecs.Project, error) {
	ret := _m.ctrl.Call(_m, "Create", _param0, _param1)
	ret0, _ := ret[0].(ecs.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockProjectFactoryRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Create", arg0, arg1)
}
